const products=[
 {id:1,name:'Golden Hour Face Oil',type:'skincare',detail:'Radiance + barrier support',price:28500,tag:'BESTSELLER',img:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=85'},
 {id:2,name:'Sculpted Pearl Hoops',type:'accessories',detail:'Gold-plated statement earrings',price:22000,tag:'NEW',img:'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=600&q=85'},
 {id:3,name:'Cloud Cleansing Balm',type:'skincare',detail:'Melt-away botanical cleanse',price:19000,tag:'',img:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=600&q=85'},
 {id:4,name:'The Everyday Clutch',type:'accessories',detail:'Woven vegan leather',price:36500,tag:'JUST IN',img:'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=600&q=85'},
 {id:5,name:'Dewdrop Vitamin C Serum',type:'skincare',detail:'Brightening, 15% vitamin C',price:31500,tag:'NEW',img:'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=600&q=85'},
 {id:6,name:'Silk Ribbon Set',type:'accessories',detail:'Set of two satin hair bows',price:12000,tag:'',img:'https://images.unsplash.com/photo-1601592993487-3be0d541068a?auto=format&fit=crop&w=600&q=85'}
];
let cart=[];const money=n=>'₦'+n.toLocaleString('en-NG');
function render(filter='all'){const list=filter==='all'?products:filter==='new'?products.filter(p=>p.tag):products.filter(p=>p.type===filter);document.getElementById('products').innerHTML=list.map(p=>`<article class="product"><div class="product-img"><img src="${p.img}" alt="${p.name}">${p.tag?`<span class="tag">${p.tag}</span>`:''}<button class="add" onclick="add(${p.id})" aria-label="Add ${p.name} to bag">+</button></div><h3>${p.name}</h3><p>${p.detail}</p><span class="price">${money(p.price)}</span></article>`).join('')}
function add(id){const p=products.find(x=>x.id===id),inCart=cart.find(x=>x.id===id);inCart?inCart.qty++:cart.push({...p,qty:1});updateCart();showToast(`${p.name} added to your bag`)}
function updateCart(){const count=cart.reduce((n,p)=>n+p.qty,0);document.getElementById('cartCount').textContent=count;document.getElementById('cartItems').innerHTML=cart.length?cart.map(p=>`<div class="cart-line"><img src="${p.img}" alt=""><div><h4>${p.name}</h4><p>${money(p.price)} · Qty ${p.qty}</p><button class="remove" onclick="removeItem(${p.id})">Remove</button></div><strong>${money(p.price*p.qty)}</strong></div>`).join(''):'<p class="empty">Your bag is waiting for something beautiful.</p>';document.getElementById('subtotal').textContent=money(cart.reduce((n,p)=>n+p.price*p.qty,0))}
function removeItem(id){cart=cart.filter(p=>p.id!==id);updateCart()}
function showPanel(id){document.getElementById(id).classList.add('open');document.querySelector('.overlay').classList.add('show')}function closePanels(){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('open'));document.querySelector('.overlay').classList.remove('show')};function showToast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
render();document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)});document.getElementById('cartBtn').onclick=()=>showPanel('cartPanel');document.getElementById('accountBtn').onclick=()=>showPanel('accountPanel');document.querySelectorAll('.close,.overlay').forEach(x=>x.onclick=closePanels);document.getElementById('checkout').onclick=()=>cart.length?showToast('Checkout is ready to connect to Paystack or Stripe.'):showToast('Add an item to start checkout.');document.getElementById('viewAll').onclick=()=>{document.querySelector('[data-filter="all"]').click();document.getElementById('shop').scrollIntoView()};document.getElementById('emailForm').onsubmit=e=>{e.preventDefault();document.getElementById('formMessage').textContent='You’re on the list — welcome to the ritual.';e.target.reset()};
